Project1/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Employee__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>User__r.FirstName &amp; &quot; &quot; &amp; User__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1/force-app/main/default/classes/CustomLookUpController.cls
public class CustomLookUpController {
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, List <sObject> alreadySelected) {
       // system.debug('ObjectName-->' + ObjectName);
                
        //use escapeSingleQuotes to prevent SQLInject
        String searchKey = String.escapeSingleQuotes(searchKeyWord) + '%';
        
        List < sObject > returnList = new List < sObject > ();
       	String sQuery =  'SELECT Id, Name, Full_Name__c, User__c FROM Employee__c';
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 10   
        if (searchKeyWord != '' ){
            sQuery += ' where Full_Name__c LIKE: searchKey ';
        }
        if(alreadySelected !=null && alreadySelected.size()>0){
           set<Id> excludeSet=new set<Id>() ;
        	for (sObject sObj : alreadySelected){
            	Employee__c myEmp = (Employee__c) sObj;
            	excludeSet.add(myEmp.Id);
        	}

            sQuery += 'AND Id NOT IN :excludeSet ';
        }
        sQuery +='ORDER BY createdDate DESC limit 10';
        
        List < sObject > lstOfRecords = Database.query(sQuery);
        
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
}