Project1/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Inventory__c/fields/Inventory_Amount__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Amount__c</fullName>
    <label>Inventory Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Inventory__c/fields/Inventory_Unit__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Unit__c</fullName>
    <label>Inventory Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Baguette Bread</fullName>
            </value>
            <value>
                <fullName>Brioche Bread</fullName>
            </value>
            <value>
                <fullName>Rye Bread</fullName>
            </value>
            <value>
                <fullName>Sourdough Bread</fullName>
            </value>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Steak</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Ham</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Coke Product</fullName>
            </value>
            <value>
                <fullName>Cups</fullName>
            </value>
            <value>
                <fullName>Plates</fullName>
            </value>
            <value>
                <fullName>Eating Utensils</fullName>
            </value>
            <value>
                <fullName>Bleach</fullName>
            </value>
            <value>
                <fullName>Windex</fullName>
            </value>
            <value>
                <fullName>Oxyclean</fullName>
            </value>
            <value>
                <fullName>Pending Inventory Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Supply_Request__c/Supply_Request__c.object-meta.xml
<CustomObject>
    <label>Supply Request</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Supply Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Supply_Request__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCompleted</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Supply_Request__c/fields/SupplyRequest__c.field-meta.xml
<CustomField>
    <fullName>SupplyRequest__c</fullName>
    <label>SupplyRequest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestedSupply</valueSetName>
    </valueSet>
</CustomField>

Project1/Project2/metadata/unpackaged/unpackaged/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Bread_Type__c</fullName>
        <label>Bread Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baguette</fullName>
                </value>
                <value>
                    <fullName>Brioche</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Sourdough</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drink__c</fullName>
        <label>Drink</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Drink_Included__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Coke Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meat_Type__c</fullName>
        <label>Meat Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beef</fullName>
                </value>
                <value>
                    <fullName>Steak</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Ham</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Tr-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/globalValueSets/RequestedSupply.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Meat</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Utensils</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaning Supplies</fullName>
    </customValue>
    <masterLabel>RequestedSupply</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/PopularInventoryControler.cls
public class PopularInventoryControler {
	
    public List<PopularityObject> invPickList{get;set;} 
    
    public void CreateOrder() {
        // going to make a bunch of supply requests
        List<Supply_Request__c> neededSupplies = new List<Supply_Request__c>();
        Supply_Request__c supplyOrder = new Supply_Request__c();
        
        supplyOrder.IsCompleted__c = false;        
		// we need to know which items and how much        
        for (PopularityObject item: invPickList){
            if(item.RecAmt>0) {
		        supplyOrder.SupplyRequest__c = item.Name;
            }
        }
        insert neededSupplies;
    }

    //Initializing
    public PopularInventoryControler()
    {
        // inventory Matrix
        invPickList = new List<PopularityObject>();
       
	    // finding the picklist values and fill invPickList with their strings
        Schema.DescribeFieldResult fieldResult = Inventory__c.Inventory_Unit__c.getDescribe();
        list<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry plv: ple) {
            // filling top row with default picklist
            PopularityObject nextItem = new PopularityObject();
            nextItem.customInit();
            nextItem.Name = plv.getLabel();
            invPickList.add(nextItem);
        }      

        // update inventory in the Popularity objects
        List<Inventory__c> InventoryList =[Select Inventory_Unit__c, Inventory_Amount__c From Inventory__c];
        for(Inventory__c inv:InventoryList){
            for(PopularityObject i:invPickList){
                if (inv.Inventory_Unit__c == i.Name) {
                    i.InvAmt = inv.Inventory_Amount__c;
					break;                    
                }
            }
        }
        
        // count orders and record in the Popularity objects
        List<Transaction__c> transactionList =[Select Bread_Type__c, Drink__c, Meat_Type__c From Transaction__c];
        for(Transaction__c t:transactionList){
            for(PopularityObject i:invPickList){
                if (t.Bread_Type__c == i.Name || t.Drink__c == i.Name || t.Meat_Type__c == i.Name) {
                    i.SoldAmt++;
                    i.UpdateRecAmt();                    
                    break;                    
                }
            }
        }

    }
    
    

    
}